#!/bin/bash

## Author : Aditya Shakya
## Email  : adi1090x@gmail.com

#colors
R='\033[1;31m'
B='\033[1;34m'
C='\033[0;36m'
G='\033[1;32m'
W='\033[1;37m'
Y='\033[1;33m'

DIR="$(pwd)"

echo
echo -e $B"   ░▀█▀░█▀▄░█▀█░█▀█░█▀▄░█▀█░█▄█░▀█▀░▀▀█░█▀▀░█▀▄"
echo -e $B"   ░░█░░█▀▄░█▀█░█░█░█░█░█░█░█░█░░█░░▄▀░░█▀▀░█▀▄"
echo -e $B"   ░░▀░░▀░▀░▀░▀░▀░▀░▀▀░░▀▀▀░▀░▀░▀▀▀░▀▀▀░▀▀▀░▀░▀"
echo
echo -e $B"   [$R*$B] By-$Y Aditya Shakya $R//$Y adi1090x"
echo

echo -e $G"   [*] Installing tRandomizer..."
echo

if [ ! -d $HOME/.config/termite ]; then
mkdir $HOME/.config/termite
fi

# User Config
mv $HOME/.config/termite/config $HOME/.config/termite/your.config
cp $DIR/config $HOME/.config/termite/config

sudo mkdir /usr/share/tRandomizer

sudo cp -r $DIR/colors /usr/share/tRandomizer
sudo cp -r $DIR/tRandomizer /usr/share/tRandomizer/tRandomizer

sudo chmod +x /usr/share/tRandomizer/tRandomizer
sudo ln -s /usr/share/tRandomizer/tRandomizer /usr/bin/tRandomizer

echo -e $G"   [*] Setup Completed."
echo
echo -e $Y"   [*] Now You Can Run This Program By Just typing 'tRandomizer'."
echo
echo -e $Y"   [*] Also You Can Add 'tRandomizer -c' To Your Shell Config File (.zshrc, .bashrc)To Change Colors Each Time You Execute Termite."
echo
echo -e $G"   [*] Developed By$R Aditya Shakya."
echo
